### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by DataDrug** [TalAloni/RawDiskCopier#1]
Hey,

I have been trying to open your .sln file but first i had a issue with DiskAccessLibrary.dll and Utilities.dll missing (wich I've grabbed from your other project) but now, when I try to debug or compile i get this error:

Error	CS0200	Property or indexer 'Disk.IsReadOnly' cannot be assigned to -- it is read only	on MainForm.cs	246.

I'm not a C# expert, could your provide me a way out ? 🙉

**Comment by TalAloni** [comment]
Hi, you are attempting to use a newer DiskAccessLibrary than the one
compatible with this project,
I'll update the project soon, in the meantime you can use an older version
of DiskAccessLibrary.

Tal

**Comment by DataDrug** [comment]
> Hi, you are attempting to use a newer DiskAccessLibrary than the one compatible with this project, I'll update the project soon, in the meantime you can use an older version of DiskAccessLibrary. Tal
> […](#)

Where can I download it?

**Comment by TalAloni** [comment]
On Github. I have a project called Dynamic Disk Partitioner.

**Comment by TalAloni** [comment]
Hi, I have committed the fix to master, you can now use the latest version of DiskAccessLibrary

**Comment by DataDrug** [comment]
thank's.
