### ISSUE TITLE
mono/net 3.x to .net 4.x

### ISSUE THREAD

**Issue by IBIT-ZEE** [TalAloni/RawDiskCopier#2]
Hi Tal...

When using your applications in Windows 10
they allways prompt/ask/need for ,net 3.x installation...

Can you please compile them with the latest VS-Community 
and target .net 4.0... so they work out-of-the-box!
(just download and execute)

( in some organizations there are policies 
that restrict the users form installing 
or even updating the system... 
and .net 4.0 is native in Windows 10 )

Thanks!

**Comment by Natalia-Oreiro** [comment]
Very good idea 👍

**Comment by TalAloni** [comment]
Done. the 1.0.6 release contain both .NET 2.0 and .NET 4.0 executables.
